{{ if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "docs.fullname" . }}
  labels:
     {{- include "docs.labels" . | nindent 6 }}
spec:
  selector:
    matchLabels:
     {{- include "docs.labels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
{{ end }}