module.exports = [
  {
    id: 'cost-management',
    title: 'Cost Management',
    description: 'Track cloud spending, budgets, billing, and funding sources across accounts.',
    prefixes: ['spends', 'spend', 'billing', 'budget', 'businessunit_funding', 'project_funding', 'funding'],
  },
  {
    id: 'anomalies',
    title: 'Anomalies',
    description: 'Detect and manage cost and operational anomalies.',
    prefixes: ['anomaly', 'anamoly'],
  },
  {
    id: 'events-incidents',
    title: 'Events & Incidents',
    description: 'Event ingestion, alerting rules, triage, severity classification, and incident insights.',
    prefixes: ['event', 'events', 'alert', 'insight'],
  },
  {
    id: 'recommendations',
    title: 'Recommendations',
    description: 'Cost optimization, security, and misconfiguration recommendations with estimated savings.',
    prefixes: ['recommendation', 'apply_recommendations'],
  },
  {
    id: 'cloud-infrastructure',
    title: 'Cloud Infrastructure',
    description: 'Cloud accounts, resources, provider-specific operations (AWS, Azure), and resource metrics.',
    prefixes: ['cloud', 'aws', 'azure', 'active_resources'],
  },
  {
    id: 'kubernetes',
    title: 'Kubernetes',
    description: 'K8s clusters, workloads, pods, nodes, namespaces, and cluster management.',
    prefixes: ['k8s'],
  },
  {
    id: 'automation',
    title: 'Automation',
    description: 'Auto-pilot policies, playbooks, runbooks, workflows, and optimization rules.',
    prefixes: ['auto_pilot', 'auto_playbook', 'auto_runbook', 'auto_optimize', 'autopilot', 'workflow'],
  },
  {
    id: 'agents',
    title: 'Agents',
    description: 'Agent deployment, configuration, playbooks, tasks, and audit logs.',
    prefixes: ['agent'],
  },
  {
    id: 'ai-llm',
    title: 'AI & LLM',
    description: 'AI conversations, knowledge bases, RAG, LLM agents, tools, and root cause analysis.',
    prefixes: ['ai', 'llm', 'knowledge', 'kg'],
  },
  {
    id: 'observability',
    title: 'Observability',
    description: 'Logs, metrics, traces, application profiles, and service maps.',
    prefixes: ['metrics', 'metric', 'logs', 'log', 'traces', 'trace', 'application', 'ml_get'],
  },
  {
    id: 'compliance-security',
    title: 'Compliance & Security',
    description: 'Compliance standards, security checks, findings, and alertmanager configurations.',
    prefixes: ['compliance', 'security', 'alertmanager'],
  },
  {
    id: 'tickets',
    title: 'Tickets',
    description: 'Ticket creation, management, and integrations with external issue trackers.',
    prefixes: ['ticket', 'tickets'],
  },
  {
    id: 'notifications',
    title: 'Notifications',
    description: 'Notification channels, delivery rules, and user notification preferences.',
    prefixes: ['notification', 'notifications', 'sent_notification', 'messaging'],
  },
  {
    id: 'org-users',
    title: 'Organization & Users',
    description: 'Users, tenants, business units, roles, groups, projects, and authentication.',
    prefixes: [
      'user', 'users', 'tenant', 'business_unit', 'businessunit',
      'role', 'roles', 'group_role', 'user_group', 'usergroup',
      'project', 'auth', 'admin_get',
    ],
  },
  {
    id: 'integrations',
    title: 'Integrations',
    description: 'Third-party integrations: Slack, MS Teams, Jira, and custom connectors.',
    prefixes: ['integration', 'integrations', 'slack', 'ms_teams', 'jira', 'get_default_provider'],
  },
  {
    id: 'configuration',
    title: 'Configuration',
    description: 'Feature flags, SLO targets, system configuration, and upgrade management.',
    prefixes: ['config', 'configuration', 'feature', 'slo', 'upgrade', 'check_license', 'etl'],
  },
  {
    id: 'data-warehouse',
    title: 'Data Warehouse',
    description: 'Data warehouse queries, pipes, databases, and query performance.',
    prefixes: ['dw', 'database'],
  },
  {
    id: 'audit',
    title: 'Audit',
    description: 'Audit logs, user action history, and system activity tracking.',
    prefixes: ['audit', 'audits'],
  },
];
